apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: tiny-url
data:
  DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "185.228.236.77,127.0.0.1,django-app,django-app.tiny-url.svc.cluster.local"
  DB_HOST: postgres
  DB_PORT: "5432"
  GUNICORN_TIMEOUT: "120"
  GUNICORN_WORKERS: "3"
  GUNICORN_WORKER_CLASS: "sync"
