apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: tiny-url-namespace
data:
  DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: "*,10.244.0.8,10.244.0.12,localhost,127.0.0.1"
  DB_HOST: postgres
  DB_PORT: "5432"
