apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
  namespace: tiny-url-namespace
spec:
  template:
    spec:
      containers:
      - name: django-migrations
        image: hassankalantari/tiny-url-django:latest
        command: ["/bin/sh", "-c", "python manage.py makemigrations URLApp && python manage.py migrate"]
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DEBUG
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DJANGO_ALLOWED_HOSTS
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: DB_PORT
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: SECRET_KEY
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DB_PASSWORD
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DATABASE_URL
      restartPolicy: Never
  backoffLimit: 5